# Generated by Django 4.2 on 2023-06-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_management",
            "0004_alter_customuser_options_customuser_profile_cover_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_cover",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_photo",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(default="user", max_length=255, null=True),
        ),
    ]
