# Generated by Django 4.2 on 2023-04-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
    ]
