# Generated by Django 4.2 on 2023-06-17 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_remove_lesson_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="course",
        ),
        migrations.RemoveField(
            model_name="text",
            name="lesson",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Exam",
        ),
        migrations.DeleteModel(
            name="Text",
        ),
    ]
