# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site_proj/protos/content_management.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)site_proj/protos/content_management.proto\x12\x12\x63ontent_management\"M\n\x18\x43reateTextContentRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\tauthor_id\x18\x03 \x01(\x05\"@\n\x19\x43reateTextContentResponse\x12\x12\n\ncontent_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"F\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"6\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x85\x01\n\x11\x43ontentManagement\x12p\n\x11\x43reateTextContent\x12,.content_management.CreateTextContentRequest\x1a-.content_management.CreateTextContentResponse2m\n\x0eUserManagement\x12[\n\nCreateUser\x12%.content_management.CreateUserRequest\x1a&.content_management.CreateUserResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'site_proj.protos.content_management_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATETEXTCONTENTREQUEST._serialized_start=65
  _CREATETEXTCONTENTREQUEST._serialized_end=142
  _CREATETEXTCONTENTRESPONSE._serialized_start=144
  _CREATETEXTCONTENTRESPONSE._serialized_end=208
  _CREATEUSERREQUEST._serialized_start=210
  _CREATEUSERREQUEST._serialized_end=280
  _CREATEUSERRESPONSE._serialized_start=282
  _CREATEUSERRESPONSE._serialized_end=336
  _CONTENTMANAGEMENT._serialized_start=339
  _CONTENTMANAGEMENT._serialized_end=472
  _USERMANAGEMENT._serialized_start=474
  _USERMANAGEMENT._serialized_end=583
# @@protoc_insertion_point(module_scope)
